apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- analysis.yaml

images:
- name: gatheraa-backend
  newName: gatheraa/backend
  newTag: latest